# permissions for end users to view yatestoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yatestoperator-viewer-role
rules:
- apiGroups:
  - view.yasuhiroabe.github.io
  resources:
  - yatestoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - view.yasuhiroabe.github.io
  resources:
  - yatestoperators/status
  verbs:
  - get
